services:
  - type: web
    name: telkom_bot
    env: python
    runtime: python
    buildCommand: |
      apt-get update && \
<<<<<<< HEAD
      apt-get install -y libgtk-4-1 libgraphene-1.0-0 libavif15 libsecret-1-0 libenchant-2-2 libmanette-0.2-0 libgles2 libgstgl-1.0-0 libgstreamer-plugins-base-1.0-0 libgstreamer-plugins-bad1.0-0 && \
=======
      apt-get install -y libgtk-4-1 libgraphene-1.0-0 libavif15 libsecret-1-0 libenchant-2-2 libmanette-0.2-0 libgles2 && \
>>>>>>> e1c232ae64f89f7e905d474469da8e1531d8dc77
      pip install -r requirements.txt && \
      playwright install
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
      - key: LOOKER_STUDIO_MSA_WSA_URL
        sync: false
      - key: LOOKER_STUDIO_PILATEN_URL
        sync: false
<<<<<<< HEAD
        
=======
>>>>>>> e1c232ae64f89f7e905d474469da8e1531d8dc77
